### ISSUE TITLE
Update `AggregationMerkleSumTree` 

### ISSUE THREAD

**Issue by enricobottazzi** [summa-dev/summa-aggregation#5]
According to the new modification on the `Tree` trait performed in summa-dev/summa-solvency#192 and summa-dev/summa-solvency#188, the `AggregationMerkleSumTree` (https://github.com/summa-dev/summa-aggregation/blob/main/src/aggregation_merkle_sum_tree.rs#L16-L21) needs to be updated to be compatible with the trait

**Comment by sifnoc** [comment]
Updated at #3
