### ISSUE TITLE
`summa-aggregation` to V1 improvements and consolidation

### ISSUE THREAD

**Issue by enricobottazzi** [summa-dev/summa-aggregation#7]
UPDATE 6/11

Perform parallelization inside a new summa-aggregation repo (using Docker Swarm)

- `Workers` to build mini-trees
- `Orchestrator` to aggregate mini-trees in `AggregationTree` and build a Round starting from the `AggregationTree`

**Comment by sifnoc** [comment]
It's updated at #3
